# zprof によるプロファイリングの実行
# 未使用時はコメントアウトしておく
# zmodload zsh/zprof && zprof

# dotfiles までのパス
export DOTFILES=$HOME/dotfiles

source $DOTFILES/zsh/zsh.d/00001-base.zsh
source $DOTFILES/zsh/zsh.d/00050-path.zsh
source $DOTFILES/zsh/zsh.d/00075-anyenv.zsh
source $DOTFILES/zsh/zsh.d/00100-aliases.zsh
source $DOTFILES/zsh/zsh.d/00200-colors.zsh
source $DOTFILES/zsh/zsh.d/00300-prompt.zsh
source $DOTFILES/zsh/zsh.d/00400-zplug.zsh
source $DOTFILES/zsh/zsh.d/00410-tmux.zsh
source $DOTFILES/zsh/zsh.d/00500-zsh-hooks.zsh


# なんか最後にしろというから最後に移した。
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/yanagimachi/.sdkman"
[[ -s "/Users/yanagimachi/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/yanagimachi/.sdkman/bin/sdkman-init.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/yanagimachi/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/yanagimachi/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/yanagimachi/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/yanagimachi/google-cloud-sdk/completion.zsh.inc'; fi
export PATH="/usr/local/opt/bison/bin:$PATH"

# zprof の結果を表示
# 未使用時は何も起きないのでこっちは放置でOK
if (which zprof > /dev/null) ;then
  zprof | fzf
fi
