# zprof によるプロファイリングの実行
# 未使用時はコメントアウトしておく
# zmodload zsh/zprof && zprof

# dotfiles までのパス
export DOTFILES=$HOME/dotfiles

source $DOTFILES/zsh/zsh.d/00001-base.zsh
source $DOTFILES/zsh/zsh.d/00050-path.zsh
source $DOTFILES/zsh/zsh.d/00075-anyenv.zsh
source $DOTFILES/zsh/zsh.d/00100-aliases.zsh
source $DOTFILES/zsh/zsh.d/00200-colors.zsh
source $DOTFILES/zsh/zsh.d/00300-prompt.zsh
source $DOTFILES/zsh/zsh.d/00400-zplug.zsh
source $DOTFILES/zsh/zsh.d/00410-tmux.zsh
source $DOTFILES/zsh/zsh.d/00500-zsh-hooks.zsh

# zprof の結果を表示
# 未使用時は何も起きないのでこっちは放置でOK
if (which zprof > /dev/null) ;then
  zprof | fzf
fi
